### PR TITLE
Fixed st7789_draw_line to support every direction.

### PR DESCRIPTION
**Pull request by tmoinel**
Use https://fr.wikipedia.org/wiki/Algorithme_de_trac%C3%A9_de_segment_de_Bresenham

Here small example to test it where `time` must be incremented in draw function for animation
```c
for (int a = 0; a < 360; a += 10) 
{
  const float r0 = 20.0;
  const float r1 = 100.0;
  float ar= (float)((a + time)%360) * M_PI / 180.0;
  int x0 = (int)(120.0 + cosf(ar) * r0);
  int y0 = (int)(120.0 + sinf(ar) * r0);
  int x1 = (int)(120.0 + cosf(ar) * r1);
  int y1 = (int)(120.0 + sinf(ar) * r1);
  widget_draw_line(p_widget, x0,y0,x1,y1, RGB(0x8,0xf,0xa));
}
```

### CODE REVIEW

**Comment by virtualabs** [comment]
Thanks for this fix @tmoinel ! Tested it on my twatch, works like a charm !

**Comment by tobozo** [comment]
probably irrelevant given that it's a short loop but `M_PI / 180.0` doesn't need to be calculated 36 times

```C
static const float deg2rad = M_PI / 180.0;
```

**Comment by virtualabs** [comment]
Yep, but it's just an example @tmoinel gave not some code present in this pull request :smile:

**Comment by tobozo** [comment]
another interesting line algorithm to add would be [Xiaolin Wu's](https://en.wikipedia.org/wiki/Xiaolin_Wu%27s_line_algorithm), it needs a gamma table though

**Pull request merged**
